apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-public
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: "/nginx-public" ## cache verify against this, not SHA 
    argocd.argoproj.io/sync-waves: "-100" # -INF, -2147483648, ..., 0, ..., 2147483647, +INF
    argocd.argoproj.io/compare-options: >- 
      ServerSideDiff=true,
      IncludeMutationWebhook=true     
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-public

  sources:
  - repoURL: git@github.com:graysievert-lab/experiment-k8s-bootstrapping-app-of-apps-directory.git
    targetRevision: HEAD 
    ref: values

  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 4.12.0
    chart: nginx-public
    helm:
      valueFiles:
      - $values/nginx-public/values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:     
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - ServerSideApply=true